title: Chisom Stanley
logo: imgphoto.jpeg
description: A Data Scientist and Analyst who enjoys turning raw data into meaningful insight that drives better decisions. I build practical, scalable solutions across analytics, business intelligence, and machine learning. With Python, SQL, Excel, and Power BI, I turn complex information into clear, accurate, and actionable outcomes.
#show download: true
#google_analytics:
theme: jekyll-theme-minimal
